routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();


Route::get('/', function () {
    return redirect(route('dashboard'));
});

Route::resource('barcode', 'barcodeController');
Route::resource('configuracion', 'ConfiguracionesController');
Route::resource('control', 'ControlEmpleadosContorller');
Route::get('controlListar', 'ControlEmpleadosContorller@controlListar');

    Route::resource('pruebas', 'PruebasController');
    Route::resource('postulados', 'PostuladosController');

    Route::resource('convocatoria', 'ConvocatoriasController');
Route::group(['middleware'=>'auth'],function (){

    Route::get('dashboard','HomeController@index')->name('dashboard');
    Route::resource('perfiles', 'PerfilesController');
    Route::get('perfilesdel/{nombre}/{id}', 'PerfilesController@destroy')->name('perfilesdel');
    Route::resource('users', 'UsersController');
    Route::get('estado/{nombre}/{id}', 'UsersController@estado')->name('estado');

    Route::resource('evaluarR', 'EvaluarRController');
    Route::get('evaluarRen', 'EvaluarRController@listing');
    Route::get('respuesta/{idres}/{idhoja}/{idp}', 'EvaluarRController@setRespuesta')->name('respuesta');
    Route::resource('preguntare', 'preguntareController');

    Route::resource('hoja_de_vida', 'HojadeVidaController');

    Route::get('listarHojas', 'HojadeVidaController@listarHojas');

    Route::resource('liquidacion', 'LiquidacionController');

    Route::resource('administradora', 'AdministradorasController');
    Route::get('admindel/{nombre}/{id}', 'AdministradorasController@destroy')->name('admindel');

    Route::resource('tipoContrato', 'TiposContratosController');
    Route::get('tiposContratosdel/{nombre}/{id}', 'TiposContratosController@destroy')->name('tiposContratosdel');

    Route::resource('tipoSalario', 'TiposSalariosController');
    Route::get('tiposSalariosdel/{nombre}/{id}', 'TiposSalariosController@destroy')->name('tiposSalariosdel');

    /**
    * Rutas para crud altas y bajas
    */

    Route::get('altasbajasdel/{nombre}/{id}', 'TiposAltasBajasController@destroy')->name('altasbajasdel');
    Route::resource('tipos_altas_bajas', 'TiposAltasBajasController');

    /**
    * Rutas para aplicar las altas y bajas a un empleado
    */

    Route::get('registrodel/{nombre}/{id}', 'RegistroAltasBajasController@destroy')->name('registrodel');
    Route::resource('aplicar_altas_bajas', 'RegistroAltasBajasController');
    Route::get('listarNovedades', 'RegistroAltasBajasController@show2');
    Route::get('novedadescreate/{id}', 'RegistroAltasBajasController@create')->name('novedadescreate');


    Route::resource('contratos', 'ContratosController');
    Route::get('contratosdel/{p_nombre}/{p_apellido}/{s_apellido}/{id}/', 'ContratosController@destroy')->name('contratosdel');
    Route::get('contratosdownload/{file}', 'ContratosController@download')->name('contratosdownload');

    Route::get('cargar_postulados', 'ContratosController@cargar_postulados');
    Route::get('paisContrato/{id}', 'ContratosController@getDepartamentos')->name('paisContrato');


    Route::get('departamentoContrato/{id}', 'ContratosController@getCiudades')->name('departamentoContrato');
    Route::get('contratosshow/{id}', 'ContratosController@show')->name('contratosshow');



    Route::resource('festivos', 'FestivosController');
    Route::get('festivodel/{nombre}/{id}', 'FestivosController@destroy')->name('festivodel');

    /**
    * Rutas para registrar vacaciones
    */

    Route::resource('registrar_vacaciones', 'VacacionesController');
    Route::get('listar_vacaciones', 'VacacionesController@listar_vacaciones');
    Route::get('registrar_vacaciones/estadoVacaciones/{nombre}/{id}', 'VacacionesController@estado')->name('registrar_vacaciones/estadoVacaciones');
    Route::get('getfechaentrada/{dias}/{fecha}', 'VacacionesController@getFechaEntrada')->name('getfechaentrada');

    /**
     * Departamentos
     */
    Route::resource('depar', 'DepartamentosController');
    Route::get('deparE/{nombre}/{id}/', 'DepartamentosController@destroy')->name('deparE');

    /**
     * Vacantes
     */
    Route::resource('vacantes', 'VacantesController');
    Route::get('vacantesdel/{nombre}/{id}/', 'VacantesController@destroy')->name('vacantesdel');
    Route::get('ver_vacantes', 'VacantesController@ver_vacantes')->name('ver_vacantes');

    /**
     * Portulados
     */
    Route::resource('postulados', 'PostuladosController');
    Route::get('postular/{id_user}/{id_vacante}', 'PostuladosController@postular')->name('postular');

    /**
     * Areas de Interes
     */
    Route::resource('area_interes', 'AreaInteresController');
    Route::get('area_interesdel/{nombre}/{id}/', 'AreaInteresController@destroy')->name('area_interesdel');
    /**
     * Evaluaciones
     */
    Route::resource('evaluacion', 'EvaluacionesController');
    Route::resource('evalR', 'EvaluacionesController@cargar');
    Route::get('asignarEval/{id}', 'EvaluacionesController@asignarEval')->name('asignarEval');
    Route::get('asignar_empleado', 'EvaluacionesController@listing');
    Route::resource('asignar_evaluacion', 'AsignarEvaluacionController');

    /**
     * Nomina
     */
    Route::resource('nomina', 'NominaController');
    Route::post('generarNomina', 'NominaController@generarNomina')->name('generarNomina');

    Route::get('NominaShow/{id}', 'NominaController@show')->name('NominaShow');


    Route::resource('liquidacion', 'LiquidacionesController');
    Route::get('LiquidacionShow/{id}', 'LiquidacionesController@show')->name('LiquidacionShow');

    Route::resource('changePass', 'ResetPassController');
    Route::resource('carnets', 'CarnetsController');

    Route::get('gethijodepar/{id}', 'DepartamentosController@gethijodepar')->name('gethijodepar');
});




Route::get('cargar_postulados', 'ContratosController@cargar_postulados');
// Route::get('contratosshow/{id}/{tipo}', 'ContratosController@show')->name('contratosshow');

Route::get('password/reset/{token}', 'Auth\PasswordController@getReset');
Route::post('password/reset', 'Auth\PasswordController@postReset');

Route::get('password/email', 'Auth\PasswordController@getEmail');
Route::post('password/email', 'Auth\PasswordController@postEmail');

Route::get('cambiarpassword/{id}', 'UsersController@cambiar_password')->name('cambiarpassword');
Route::post('updatepassword', 'UsersController@update_password')->name('updatepassword');
Route::get('estado/{nombre}/{id}', 'UsersController@estado')->name('estado');
Route::get('validaremail','UsersController@validar_email')->name('validaremail');

Route::resource('evaluar', 'EvaluarController');


Route::resource('convocatorias', 'ConvocatoriasController');
Route::get('v_postulados/{id}', 'ConvocatoriasController@getPostulados')->name('v_postulados');
Route::get('v_postulados_area_int/{id}', 'ConvocatoriasController@getPostulados_area_int')->name('v_postulados_area_int');




// Route::resource('login', 'LoginController');
Route::get('logout', 'LoginController@logout')->name('logout');

Route::resource('mail', 'MailController');

Route::get('paisanidado/{id}', 'HojadeVidaController@getDepartamentos')->name('paisanidado');
Route::get('departamentoanidado/{id}', 'HojadeVidaController@getCiudades')->name('departamentoanidado');
Route::get('suspostulaciones/{id}', 'HojadeVidaController@susPostulaciones')->name('suspostulaciones');
Route::get('susconvocatorias/{id}', 'HojadeVidaController@susConvocatorias')->name('susconvocatorias');


Route::get('estado_postulado','VacantesController@estado_postulado')->name('estado_postulado');



Route::resource('cargos', 'CargosController');
Route::get('cargosE/{nombre}/{id}/', 'CargosController@destroy')->name('cargosE');

Route::resource('capa', 'CapacitacionesController');
Route::get('capaE/{nombre}/{id}/', 'CapacitacionesController@destroy')->name('capaE');

Route::resource('respuesta', 'RespuestasController');
Route::get('respuestasAdmin', 'RespuestasController@administrar_respuestas')->name('respuestasAdmin');
Route::get('respuestasAdmin2', 'RespuestasController@listing')->name('respuestasAdmin2');
Route::get('responder', 'RespuestasController@index')->name('responder');
Route::get('cargar_evaluaciones', 'RespuestasController@cargar_evaluaciones');
Route::post('presentar_evaluacion', 'RespuestasController@presentar_evaluacion')->name('presentar_evaluacion');

Route::get('realizarEval/{id}', 'EvaluacionesController@realizarEval')->name('realizarEval');






Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Http/Controllers/ContratosController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Requests;
use App\Http\Controllers\Controller;
use App\Contratos;
use App\Hojadevida;
use App\Cargos;
use App\User;
use App\Paises;
use App\Departamentos;
use App\Ciudades;
use App\TiposContratos;
use App\TiposSalarios;
use App\Administradoras;
use App\Archivos;
use Session;
use Redirect;
use DB;

class ContratosController extends Controller {

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index() {
        $id = auth()->user()->id_perfil == 4  ? auth()->user()->id : false;
        $contratos = Contratos::select(
                    'hojas_vidas.*',
                    'contratos.*',
                    'contratos.id as id_contrato',
                    'tc.descripcion AS descripcion_tipo'
                    )
                ->join('hojas_vidas', 'hojas_vidas.id', '=', 'contratos.id_hojavida')
                ->join('tipos_contratos AS tc', 'tc.id', '=', 'contratos.id_tipo_contrato')
            ->when($id, function ($query, $id) {
                return $query->where('hojas_vidas.id_user', auth()->user()->id);
            })
                ->get();
        return view('contratos.administrar', compact('contratos'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create() {
        $modificando = 0;
        $paises = Paises::pluck('nombre','id')->all();
        $departamentos = Departamentos::pluck('nombre','id')->all();
        $ciudades = Ciudades::pluck('nombre','id')->all();
        $cargos = Cargos::pluck('nombre', 'id')->toArray();
        $tiposContratos = TiposContratos::pluck('descripcion', 'id')->toArray();
        $tiposSalarios = TiposSalarios::pluck('descripcion', 'id')->toArray();
        $administradoraSalud = Administradoras::where('tipo',1)->pluck('nombre','id')->toArray();
        $administradoraPension = Administradoras::where('tipo',2)->pluck('nombre','id')->toArray();
        return view('contratos.crear',
            compact(
                'hojasdevida',
                'modificando',
                'cargos',
                'tiposContratos',
                'administradoraSalud',
                'administradoraPension',
                'paises',
                'departamentos',
                'tiposSalarios',
                'ciudades'
            )
        );
    }

    public function cargar_postulados() {
        $hojasdevida
            = Hojadevida::select(
                'hojas_vidas.id',
                'p_nombre',
                's_nombre',
                'p_apellido',
                's_apellido',
                'tipo_doc',
                'doc'
            )
            ->join('users AS u', 'u.id', '=', 'hojas_vidas.id_user')
            ->get();
        return response()->json($hojasdevida->toArray());
    }

    public function retorno() {
        $script = "<script>\n";
        $script.= "window.parent.location.href = '/contratos'; \n";
        $script.= "</script>\n";
        echo $script;
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request) {
        $archivos = Archivos::create([
            'contenido' => \File::get($request['documento']),
            'extension' => '',
            'nombre_archivo' => $request['documento']->getClientOriginalName(),
        ])->id;

        $request['documentos'] = $archivos;

        $contratos = Contratos::create($request->all());
        if ($contratos) {
            $id_user
                = Hojadevida::select('id_user')->where('id', $request['id_hojavida'])->get();
            $id_usuario = $id_user[0]->id_user;
            $usuario = User::find($id_usuario);
            $usuario->fill([
                'id_perfil' => 4
            ]);
            $usuario->save();
            Session::flash('message-success', 'El contrato fue creado correctamente');
        } else {
            Session::flash('message-error', 'El contrato no se pudo crear');
        }
        return $this->retorno();
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id) {
        $contratos = Contratos::select()
                ->join('hojas_vidas AS h', 'h.id', '=', 'contratos.id_hojavida')
                ->join('cargos', 'cargos.id', '=', 'contratos.id_cargo')
                ->where('contratos.id', $id)
                ->get();
        $contrato = $contratos[0];
        return view('contratos.tipos.contrato', compact('contrato'));
    }

    public function download($file) {
        // \Storage::disk('imgContrato')->delete('*');
        $datos = explode(',', $file);
        $contenido = DB::table('archivos')->select('contenido','nombre_archivo')->where('id', '=', $datos[0])->get()->toArray();
        \Storage::disk('imgContrato')->put($datos[1].'-'.$contenido[0]->nombre_archivo, $contenido[0]->contenido);
        $file_path = public_path('fotos/contratos/'.$datos[1].'-'.$contenido[0]->nombre_archivo);
        return response()->download($file_path);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id) {
        $modificando = 1;
        $paises = Paises::pluck('nombre','id')->all();
        $departamentos = Departamentos::pluck('nombre','id')->all();
        $ciudades = Ciudades::pluck('nombre','id')->all();
        $cargos = Cargos::pluck('nombre', 'id')->toArray();
        $tiposContratos = TiposContratos::pluck('descripcion', 'id')->toArray();
        $tiposSalarios = TiposSalarios::pluck('descripcion', 'id')->toArray();
        $administradoraSalud = Administradoras::where('tipo',1)->pluck('nombre','id')->toArray();
        $administradoraPension = Administradoras::where('tipo',2)->pluck('nombre','id')->toArray();
        $contratos = Contratos::find($id);
        return view(
            'contratos.actualizar',
            compact(
                'contratos',
                'modificando',
                'hojasdevida',
                'cargos',
                'tiposContratos',
                'administradoraSalud',
                'administradoraPension',
                'paises',
                'departamentos',
                'tiposSalarios',
                'ciudades'
            )
        );
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id) {
        $contratos = Contratos::find($id);
        $contratos->fill($request->all());
        if($contratos->save()){
            Session::flash('message-success','El contrato fue actualizado correctamente');
        }else {
            Session::flash('message-error','El contrato no pudo ser actualizado');
        }
        return $this->retorno();
    }



    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($p_nombre, $p_apellido, $s_apellido, $id) {
        $contratos = Contratos::find($id);
        $contratos->fill([
            'estado' => 0
        ]);
        if($contratos->save()){
            Session::flash('message-success','El contrato de '.$p_nombre.' '.$p_apellido.' '.$s_apellido.' fue finalizado correctamente');
        }else{
            Session::flash('message-error','El contrato no se pudo finalizar');
        }
        return Redirect::to('/contratos');
    }

    public function getDepartamentos(Request $request, $id) {
        if ($request->ajax()) {
            $departamentos = Departamentos::where('id_pais', $id)->get();
            return response()->json($departamentos);
        }
    }

    public function getCiudades(Request $request, $id) {
        if ($request->ajax()) {
            $ciudades = Ciudades::where('id_departamento', $id)->get();
            return response()->json($ciudades);
        }
    }
}

resources/views/contratos/actualizar.blade.php
@extends('layouts.app')
@section('titleForm','Actualizar Contrato')
@section('content')
{!! Form::model($contratos,['route' => ['contratos.update',$contratos->id], 'method'=>'PUT', 'class'=>'form-horizontal', 'id'=>'frm', 'name'=>'frm']) !!}
@include('contratos.forms.form_contratos')
<div class="form-group" align='center'>
    {!!Form::submit('Actualizar',['class'=>'btn btn-sm btn-primary'])!!}
    <button type="button"  onclick="window.parent.location.href = '/contratos'" class="btn btn-sm btn-warning">Cancelar</button>
</div>
{!! Form::close() !!}
@endsection
@section('includesCss')
    <link href="{{asset('vendors/iCheck/skins/flat/green.css')}}" rel="stylesheet">
    <link href="{{asset('vendors/bootstrap-daterangepicker/daterangepicker.css')}}" rel="stylesheet">
@endsection
@section('includesScripts')
    <script src="{{asset('vendors/moment/min/moment.min.js')}}"></script>
    <script src="{{asset('vendors/bootstrap-daterangepicker/daterangepicker.js')}}"></script>
@endsection

resources/views/contratos/administrar.blade.php
@extends('layouts.app')
@section('titleForm','Administrar Contratos')
@section('titleTab')
    <div class="title_right">
        <div class="col-md-6 col-sm-6 col-xs-12 form-group pull-right top_search">
            <div class="input-group">
                <a class="form-control" placeholder="Search for...">Crear Contratos</a>
                <span class="input-group-btn">
                    {!!Html::decode(
                        link_to_route(
                        'contratos.create',
                        '<button class="btn btn-sm btn-warning"><i class="fa fa-plus-square"></i> <span style="color:#FFFFFF";>Agregar</span></button>',
                        [],
                        ['class'=>'']
                    ))!!}
                </span>
            </div>
        </div>
    </div>
@endsection
@section('content')
    <!-- page content -->
    <div class="center_col" role="main">
      <div class="">

        <div class="clearfix"></div>

        <div class="row">
          <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="x_panel">
              <div class="x_content">
                <div class="row">
                  <div class="col-sm-12">
                    <div class="card-box table-responsive">
                      <table id="datatable-keytable" class="table table-striped table-bordered">
                        <thead>
                          <tr>
                           <th>Documento</th>
                           <th>Nombres</th>
                           <th>Apellidos</th>
                           <th>Tipo contrato</th>
                           <th>Estado</th>
                           @if(2 == auth()->user()->id_perfil || 3 == auth()->user()->id_perfil)
                            <th>Acciones</th>
                           @endif
                          </tr>
                        </thead>

                        <tbody>
                            @foreach($contratos as $data)
                              <tr>
                                <td>{{$data->doc}}</td>
                                <td>{{$data->p_nombre}}</td>
                                <td>{{$data->p_apellido}}</td>
                                <td>{{$data->descripcion_tipo}}</td>
                                @if(1 == $data->estado)
                                    <td>Activo</td>
                                @endif
                                @if(0 == $data->estado)
                                    <td>Finalizado</td>
                                @endif
                                <td>
                                    {!!Html::decode(link_to_route('contratosshow', '<i class="fa fa-eye" title="Ver contrato"></i>',
                                        [$data->id,$data->tipo_contrato], ['class'=>'iframe_hojadevida']))!!}&nbsp;
                                    @if(2 == auth()->user()->id_perfil || 3 == auth()->user()->id_perfil)
                                        {!!Html::decode(link_to_route('contratosdownload', '<i class="fa fa-download" title="Descargar documentos"></i>',
                                            [$data->documentos.",".$data->doc], []))!!}&nbsp;
                                        <?php if($data->estado == 1){ ?>
                                        {!!Html::decode(link_to_route('contratos.edit', '<button class="btn-primary" title="Editar"><i class="fa fa-edit"></i></button>',
                                            [$data->id], ['class'=>'iframe']))!!}
                                        <a onclick="finContrato({{$data->id}}, 'contratosdel/{{$data->p_nombre}}/{{$data->p_apellido}}/{{$data->s_apellido}}/',
                                            'De: {{$data->p_nombre}} {{$data->p_apellido}} {{$data->s_apellido}}');">
                                            <button class="btn-danger" title="Finalizar contrato"><i class="fa fa-remove"></i></button></a>
                                        <?php } ?>
                                    @endif
                                </td>
                              </tr>
                            @endforeach
                        </tbody>
                      </table>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
@endsection
@section('includesCss')
    <link href="{{asset('vendors/pnotify/dist/pnotify.css')}}" rel="stylesheet">
    <link href="{{asset('vendors/pnotify/dist/pnotify.buttons.css')}}" rel="stylesheet">
    <link href="{{asset('vendors/pnotify/dist/pnotify.nonblock.css')}}" rel="stylesheet">
    <link href="{{asset('vendors/datatables.net-bs/css/dataTables.bootstrap.min.css')}}" rel="stylesheet">
    <link href="{{asset('vendors/datatables.net-buttons-bs/css/buttons.bootstrap.min.css')}}" rel="stylesheet">
    <link href="{{asset('vendors/datatables.net-fixedheader-bs/css/fixedHeader.bootstrap.min.css')}}" rel="stylesheet">
    <link href="{{asset('vendors/datatables.net-responsive-bs/css/responsive.bootstrap.min.css')}}" rel="stylesheet">
    <link href="{{asset('vendors/datatables.net-scroller-bs/css/scroller.bootstrap.min.css')}}" rel="stylesheet">
    <link href="{{asset('vendors/msgbox/jquery.msgbox.css')}}" rel="stylesheet">
@endsection
@section('includesScripts')
    <script src="{{asset('vendors/pnotify/dist/pnotify.js')}}"></script>
    <script src="{{asset('vendors/pnotify/dist/pnotify.buttons.js')}}"></script>
    <script src="{{asset('vendors/pnotify/dist/pnotify.nonblock.js')}}"></script>
    <script src="{{asset('vendors/datatables.net/js/jquery.dataTables.min.js')}}"></script>
    <script src="{{asset('vendors/datatables.net-bs/js/dataTables.bootstrap.min.js')}}"></script>
    <script src="{{asset('vendors/datatables.net-buttons/js/dataTables.buttons.min.js')}}"></script>
    <script src="{{asset('vendors/datatables.net-buttons-bs/js/buttons.bootstrap.min.js')}}"></script>
    <script src="{{asset('vendors/datatables.net-buttons/js/buttons.flash.min.js')}}"></script>
    <script src="{{asset('vendors/datatables.net-buttons/js/buttons.html5.min.js')}}"></script>
    <script src="{{asset('vendors/datatables.net-buttons/js/buttons.print.min.js')}}"></script>
    <script src="{{asset('vendors/datatables.net-fixedheader/js/dataTables.fixedHeader.min.js')}}"></script>
    <script src="{{asset('vendors/datatables.net-keytable/js/dataTables.keyTable.min.js')}}"></script>
    <script src="{{asset('vendors/datatables.net-responsive/js/dataTables.responsive.min.js')}}"></script>
    <script src="{{asset('vendors/datatables.net-responsive-bs/js/responsive.bootstrap.js')}}"></script>
    <script src="{{asset('vendors/datatables.net-scroller/js/dataTables.scroller.min.js')}}"></script>
    <script src="{{asset('vendors/msgbox/jquery.msgbox.js')}}"></script>
    <script src="{{asset('build/js/datatables.js')}}"></script>
    <script src="{{asset('build/js/funtionsConfirm.js')}}"></script>
@endsection

resources/views/contratos/crear.blade.php
@extends('layouts.app')
@section('titleForm','Crear Contrato')
@section('titleTab')
@endsection
@section('content')
    {!! Form::open(['route' => 'contratos.store', 'method'=>'POST','id'=>'demo-form2','name'=>'frm',
    'class'=>'form-horizontal form-label-left','novalidate','files'=>true]) !!}
        @include('contratos.forms.form_contratos')
        <div class="form-group" align='center'>
            {!!Form::submit('Crear',['class'=>'btn btn-sm btn-success'])!!}
            <button type="button"  onclick="window.parent.location.href = '/contratos'" class="btn btn-sm btn-warning">Cancelar</button>
        </div>
    {!!Form::close()!!}
@endsection
@section('includesCss')
    <link href="{{asset('vendors/iCheck/skins/flat/green.css')}}" rel="stylesheet">
    <link href="{{asset('vendors/iCheck/skins/flat/green.css')}}" rel="stylesheet">
    <link href="{{asset('vendors/bootstrap-daterangepicker/daterangepicker.css')}}" rel="stylesheet">
    <link href="{{asset('vendors/select/select2.min.css')}}" rel="stylesheet">
@endsection
@section('includesScripts')
    <script src="{{asset('vendors/moment/min/moment.min.js')}}"></script>
    <script src="{{asset('vendors/iCheck/icheck.min.js')}}"></script>
    <script src="{{asset('vendors/bootstrap-daterangepicker/daterangepicker.js')}}"></script>
    <script src="{{asset('vendors/validator/validator.js')}}"></script>
    <script src="{{asset('vendors/select/select2.full.js')}}"></script>
    <script type="text/javascript">

        $(document).ready(function(){
            cargar_postulados();
            $(".select").select2({
                allowClear: true
            });

            $("#fecha_fin").change(function (event) {
                if ($("#fecha_fin").val() < $("#fecha_inicio").val()) {
                    alert("Fceha Final no puede ser menor ala fecha inical");
                    $("#fecha_fin").val('');
                    $("#fecha_fin").focus();
                }
                
            });
            


            $("#pais").change(function (event) {
                $.get("/paisContrato/" + event.target.value + "", function (response, torres) {
                    $("#departamento").empty();
                    if (response.length !== 0) {
                        $("#departamento").append("<option value=''>" + 'Seleccione...' + "</option>");
                        for (i = 0; response.length > i; i++) {
                            $("#departamento").append("<option value='" + response[i].id + "'>" + response[i].nombre + "</option>");
                        }
                    } else {
                        $("#departamento").append("<option value=''> No hay registros </option>");
                    }
                });
            });

            $("#departamento").change(function (event) {
                $.get("/departamentoContrato/" + event.target.value + "", function (response, torres) {
                    $("#ciudad").empty();
                    if (response.length !== 0) {
                        $("#ciudad").append("<option value=''>" + 'Seleccione...' + "</option>");
                        for (i = 0; response.length > i; i++) {
                            $("#ciudad").append("<option value='" + response[i].id + "'>" + response[i].nombre + "</option>");
                        }
                    } else {
                        $("#ciudad").append("<option value=''> No hay registros </option>");
                    }
                });
            });

        });
        function cargar_postulados() {
            var Datos = $("#cargar_postulados");
            var route = "/cargar_postulados";
            $.get(route, function (res) {
                $(res).each(function (key, values) {
                    Datos.append("<option value='" + values.id + "'>" + values.p_nombre + "" + values.s_nombre + " " + values.p_apellido + " " + values.s_apellido + " " + values.tipo_doc + " " + values.doc + " </option>");

                });
            });
        }
    </script>
@endsection