routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();


Route::get('/', function () {
    return redirect(route('dashboard'));
});

Route::resource('barcode', 'barcodeController');
Route::resource('configuracion', 'ConfiguracionesController');
Route::resource('control', 'ControlEmpleadosContorller');
Route::get('controlListar', 'ControlEmpleadosContorller@controlListar');

    Route::resource('pruebas', 'PruebasController');
    Route::resource('postulados', 'PostuladosController');

    Route::resource('convocatoria', 'ConvocatoriasController');
Route::group(['middleware'=>'auth'],function (){

    Route::get('dashboard','HomeController@index')->name('dashboard');
    Route::resource('perfiles', 'PerfilesController');
    Route::get('perfilesdel/{nombre}/{id}', 'PerfilesController@destroy')->name('perfilesdel');
    Route::resource('users', 'UsersController');
    Route::get('estado/{nombre}/{id}', 'UsersController@estado')->name('estado');

    Route::resource('evaluarR', 'EvaluarRController');
    Route::get('evaluarRen', 'EvaluarRController@listing');
    Route::get('respuesta/{idres}/{idhoja}/{idp}', 'EvaluarRController@setRespuesta')->name('respuesta');
    Route::resource('preguntare', 'preguntareController');

    Route::resource('hoja_de_vida', 'HojadeVidaController');

    Route::get('listarHojas', 'HojadeVidaController@listarHojas');

    Route::resource('liquidacion', 'LiquidacionController');

    Route::resource('administradora', 'AdministradorasController');
    Route::get('admindel/{nombre}/{id}', 'AdministradorasController@destroy')->name('admindel');

    Route::resource('tipoContrato', 'TiposContratosController');
    Route::get('tiposContratosdel/{nombre}/{id}', 'TiposContratosController@destroy')->name('tiposContratosdel');

    Route::resource('tipoSalario', 'TiposSalariosController');
    Route::get('tiposSalariosdel/{nombre}/{id}', 'TiposSalariosController@destroy')->name('tiposSalariosdel');

    /**
    * Rutas para crud altas y bajas
    */

    Route::get('altasbajasdel/{nombre}/{id}', 'TiposAltasBajasController@destroy')->name('altasbajasdel');
    Route::resource('tipos_altas_bajas', 'TiposAltasBajasController');

    /**
    * Rutas para aplicar las altas y bajas a un empleado
    */

    Route::get('registrodel/{nombre}/{id}', 'RegistroAltasBajasController@destroy')->name('registrodel');
    Route::resource('aplicar_altas_bajas', 'RegistroAltasBajasController');
    Route::get('listarNovedades', 'RegistroAltasBajasController@show2');
    Route::get('novedadescreate/{id}', 'RegistroAltasBajasController@create')->name('novedadescreate');


    Route::resource('contratos', 'ContratosController');
    Route::get('contratosdel/{p_nombre}/{p_apellido}/{s_apellido}/{id}/', 'ContratosController@destroy')->name('contratosdel');
    Route::get('contratosdownload/{file}', 'ContratosController@download')->name('contratosdownload');

    Route::get('cargar_postulados', 'ContratosController@cargar_postulados');
    Route::get('paisContrato/{id}', 'ContratosController@getDepartamentos')->name('paisContrato');


    Route::get('departamentoContrato/{id}', 'ContratosController@getCiudades')->name('departamentoContrato');
    Route::get('contratosshow/{id}', 'ContratosController@show')->name('contratosshow');



    Route::resource('festivos', 'FestivosController');
    Route::get('festivodel/{nombre}/{id}', 'FestivosController@destroy')->name('festivodel');

    /**
    * Rutas para registrar vacaciones
    */

    Route::resource('registrar_vacaciones', 'VacacionesController');
    Route::get('listar_vacaciones', 'VacacionesController@listar_vacaciones');
    Route::get('registrar_vacaciones/estadoVacaciones/{nombre}/{id}', 'VacacionesController@estado')->name('registrar_vacaciones/estadoVacaciones');
    Route::get('getfechaentrada/{dias}/{fecha}', 'VacacionesController@getFechaEntrada')->name('getfechaentrada');

    /**
     * Departamentos
     */
    Route::resource('depar', 'DepartamentosController');
    Route::get('deparE/{nombre}/{id}/', 'DepartamentosController@destroy')->name('deparE');

    /**
     * Vacantes
     */
    Route::resource('vacantes', 'VacantesController');
    Route::get('vacantesdel/{nombre}/{id}/', 'VacantesController@destroy')->name('vacantesdel');
    Route::get('ver_vacantes', 'VacantesController@ver_vacantes')->name('ver_vacantes');

    /**
     * Portulados
     */
    Route::resource('postulados', 'PostuladosController');
    Route::get('postular/{id_user}/{id_vacante}', 'PostuladosController@postular')->name('postular');

    /**
     * Areas de Interes
     */
    Route::resource('area_interes', 'AreaInteresController');
    Route::get('area_interesdel/{nombre}/{id}/', 'AreaInteresController@destroy')->name('area_interesdel');
    /**
     * Evaluaciones
     */
    Route::resource('evaluacion', 'EvaluacionesController');
    Route::resource('evalR', 'EvaluacionesController@cargar');
    Route::get('asignarEval/{id}', 'EvaluacionesController@asignarEval')->name('asignarEval');
    Route::get('asignar_empleado', 'EvaluacionesController@listing');
    Route::resource('asignar_evaluacion', 'AsignarEvaluacionController');

    /**
     * Nomina
     */
    Route::resource('nomina', 'NominaController');
    Route::post('generarNomina', 'NominaController@generarNomina')->name('generarNomina');

    Route::get('NominaShow/{id}', 'NominaController@show')->name('NominaShow');


    Route::resource('liquidacion', 'LiquidacionesController');
    Route::get('LiquidacionShow/{id}', 'LiquidacionesController@show')->name('LiquidacionShow');

    Route::resource('changePass', 'ResetPassController');
    Route::resource('carnets', 'CarnetsController');

    Route::get('gethijodepar/{id}', 'DepartamentosController@gethijodepar')->name('gethijodepar');
});




Route::get('cargar_postulados', 'ContratosController@cargar_postulados');
// Route::get('contratosshow/{id}/{tipo}', 'ContratosController@show')->name('contratosshow');

Route::get('password/reset/{token}', 'Auth\PasswordController@getReset');
Route::post('password/reset', 'Auth\PasswordController@postReset');

Route::get('password/email', 'Auth\PasswordController@getEmail');
Route::post('password/email', 'Auth\PasswordController@postEmail');

Route::get('cambiarpassword/{id}', 'UsersController@cambiar_password')->name('cambiarpassword');
Route::post('updatepassword', 'UsersController@update_password')->name('updatepassword');
Route::get('estado/{nombre}/{id}', 'UsersController@estado')->name('estado');
Route::get('validaremail','UsersController@validar_email')->name('validaremail');

Route::resource('evaluar', 'EvaluarController');


Route::resource('convocatorias', 'ConvocatoriasController');
Route::get('v_postulados/{id}', 'ConvocatoriasController@getPostulados')->name('v_postulados');
Route::get('v_postulados_area_int/{id}', 'ConvocatoriasController@getPostulados_area_int')->name('v_postulados_area_int');




// Route::resource('login', 'LoginController');
Route::get('logout', 'LoginController@logout')->name('logout');

Route::resource('mail', 'MailController');

Route::get('paisanidado/{id}', 'HojadeVidaController@getDepartamentos')->name('paisanidado');
Route::get('departamentoanidado/{id}', 'HojadeVidaController@getCiudades')->name('departamentoanidado');
Route::get('suspostulaciones/{id}', 'HojadeVidaController@susPostulaciones')->name('suspostulaciones');
Route::get('susconvocatorias/{id}', 'HojadeVidaController@susConvocatorias')->name('susconvocatorias');


Route::get('estado_postulado','VacantesController@estado_postulado')->name('estado_postulado');



Route::resource('cargos', 'CargosController');
Route::get('cargosE/{nombre}/{id}/', 'CargosController@destroy')->name('cargosE');

Route::resource('capa', 'CapacitacionesController');
Route::get('capaE/{nombre}/{id}/', 'CapacitacionesController@destroy')->name('capaE');

Route::resource('respuesta', 'RespuestasController');
Route::get('respuestasAdmin', 'RespuestasController@administrar_respuestas')->name('respuestasAdmin');
Route::get('respuestasAdmin2', 'RespuestasController@listing')->name('respuestasAdmin2');
Route::get('responder', 'RespuestasController@index')->name('responder');
Route::get('cargar_evaluaciones', 'RespuestasController@cargar_evaluaciones');
Route::post('presentar_evaluacion', 'RespuestasController@presentar_evaluacion')->name('presentar_evaluacion');

Route::get('realizarEval/{id}', 'EvaluacionesController@realizarEval')->name('realizarEval');






Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Vacaciones.php
<?php

namespace App;
use Carbon\Carbon;

use Illuminate\Database\Eloquent\Model;

class Vacaciones extends Model
{
    protected $table = 'vacaciones';
    protected $fillable = ['id','id_hojas_vidas','numero_dias','fecha_salida','fecha_entrada','remuneracion','observaciones','estado'];

    public function setFechaSalidaAttribute($value)
    {
        $this->attributes['fecha_salida'] = Carbon::createFromFormat('d-m-Y', $value)->format('Y-m-d');

    }   

    public function setFechaEntradaAttribute($value)
    {
        $this->attributes['fecha_entrada'] = Carbon::createFromFormat('d-m-Y', $value)->format('Y-m-d');

    }
}

app/Http/Controllers/VacacionesController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Requests;
use App\Hojadevida;
use App\Contratos;
use App\Vacaciones;
use App\Http\Controllers\Controller;
use Session;
use Auth;
use Hash;
use Redirect;
use Carbon\Carbon;
use DB;
class VacacionesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $empleados = Hojadevida::select('hojas_vidas.p_nombre','hojas_vidas.s_nombre','hojas_vidas.doc','hojas_vidas.id AS empleado_id','hojas_vidas.p_apellido','hojas_vidas.s_apellido')
            ->join('contratos','id_hojavida',  '=', 'hojas_vidas.id')
            ->get();

    return view('vacaciones.administrar', compact('empleados'));
    }

    public function listar_vacaciones()
    {
        $vacaciones = Vacaciones::select('vacaciones.*','hojas_vidas.id AS empleado_id')
            ->join('hojas_vidas','hojas_vidas.id', '=', 'vacaciones.id_hojas_vidas' )
            ->join('contratos','hojas_vidas.id',  '=', 'contratos.id_hojavida')
            ->where('hojas_vidas.id_user', auth()->user()->id)
            ->get();

        return view('vacaciones.listar', compact('vacaciones'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $vacaciones = Hojadevida::pluck('id')->all();
          return view('vacaciones.crear',compact('vacaciones'));
    }

    public function retorno() {
        $script = "<script>\n";
        // $script.= "window.parent.location.href = 'registrar_vacaciones/'" . Session::get('id_empleado') . "; \n";
        $script.= "window.parent.location.href = 'registrar_vacaciones/'; \n";
        $script.= "</script>\n";
        echo $script;
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $registro
            = Vacaciones::create([
                'id_hojas_vidas'=> Session::get('id_empleado'),
                'numero_dias' => $request['numero_dias'],
                'fecha_salida' => $request['fecha_salida'],
                'fecha_entrada' => $request['fecha_entrada'],
                'remuneracion' => $request['remuneracion'],
                'observaciones' => $request['observaciones'],
                'estado' => $request['estado'],
            ]);
        if($registro){
           // Session::forget('id_empleado');
            Session::flash('message-success','El registro  fue creado correctamente');
        }else{
            Session::flash('message-error','No pudeo ser creado');
        }
        return $this->retorno();
        // return Redirect::to('registrar_vacaciones/'. Session::get('id_empleado'));
    }

        public function getFechaEntrada(Request $request, $numDias, $fecha) {
        if ($request->ajax()) {
            $fecha1 = Carbon::createFromFormat('d-m-Y', $fecha)->format('Y-m-d');
            $numDias = $numDias;

            $v_festivo = DB::table('festivos')
                        ->select('dia_festivo')
                        ->where('dia_festivo', '>', '2018-10-14')
                        ->get()
                        ->toArray();

            for ($i=0; $i < count($v_festivo); $i++) {
                $festivo[] = $v_festivo[$i]->dia_festivo;
            }
            $dias_habiles = $numDias;

            while (true) {
                $fecha1 = Carbon::createFromFormat('Y-m-d', $fecha1)->addDays(1)->format('Y-m-d');
                $n_dia = Carbon::createFromFormat('Y-m-d', $fecha1)->dayOfWeek;

                if (!in_array($fecha1, $festivo) and $n_dia != 0 and $n_dia != 6) {
                    $dias_habiles -= 1;
                }
                if ($dias_habiles == 0) {
                    break;
                }
            }
            $fecha1 = Carbon::createFromFormat('Y-m-d', $fecha1)->format('d-m-Y');
            return response()->json($fecha1);
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        Session::put('id_empleado', $id);
        $empleados = Vacaciones::select('vacaciones.*','hojas_vidas.id AS empleado_id')
            ->join('hojas_vidas','hojas_vidas.id', '=', 'vacaciones.id_hojas_vidas' )
            ->join('contratos','hojas_vidas.id',  '=', 'contratos.id_hojavida')
            ->where('contratos.id_hojavida',$id)
            ->get();

        //return dd($empleados);
        return view('vacaciones.registrar', compact('empleados','id'));
    }

    /**
     * Metodo para cambiar estado
     */

    public function estado($name, $id) {
        $vac = Vacaciones::find($id);
        if($vac->estado == 1){
            $vac->fill([
                'estado' => 2
            ]);
            $vac->save();
            Session::flash('message-success','El registro '.$id.' fue cambiado de estado correctamente');
        }
        else if($vac->estado == 2){
            $vac->fill([
                'estado' => 1
            ]);
            $vac->save();
            Session::flash('message-success','El registro '.$id.' fue cambiado de estado correctamente');
        }
        return Redirect::to('registrar_vacaciones/'. Session::get('id_empleado'));
    }


    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/vacaciones/administrar.blade.php
@extends('layouts.app')
@section('titleForm','Registro de Vacaciones')
@section('titleTab')
    <div class="title_right">
        <div class="col-md-6 col-sm-6 col-xs-12 form-group pull-right top_search">
            
        </div>
    </div>
@endsection
@section('content')
    <!-- page content -->
    <div class="center_col" role="main">
      <div class="">

        <div class="clearfix"></div>

        <div class="row">
          <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="x_panel">
              <div class="x_content">
                <div class="row">
                  <div class="col-sm-12">
                    <div class="card-box table-responsive">
                      <table id="datatable-keytable" class="table table-striped table-bordered">
                        <thead>
                          <tr>
                            <th>Documento de Identidad</th>
                            <th>Nombres</th>
                            <th>Apellidos</th>
                            <th>Accion</th>
                          </tr>
                        </thead>

                        <tbody>
                            @foreach($empleados as $data)
                              <tr>
                                <td>{{ $data->doc }}</td>
                                <td>{{$data->p_nombre}} {{ $data->s_nombre }}</td>
                                <td>{{$data->p_apellido}} {{ $data->s_apellido }}</td>
                                 <td>
                                    {!!Html::decode(link_to_route('registrar_vacaciones.show',
                                    '<button class="btn-primary" title="Ver vacaciones"><i class="fa fa-eye"></i></button>', [$data->empleado_id], ['class'=>'iframe']))!!}
                                  
                                </td>
                              </tr>
                            @endforeach
                        </tbody>
                      </table>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
@endsection
@section('includesCss')
    <link href="{{asset('vendors/pnotify/dist/pnotify.css')}}" rel="stylesheet">
    <link href="{{asset('vendors/pnotify/dist/pnotify.buttons.css')}}" rel="stylesheet">
    <link href="{{asset('vendors/pnotify/dist/pnotify.nonblock.css')}}" rel="stylesheet">
    <link href="{{asset('vendors/datatables.net-bs/css/dataTables.bootstrap.min.css')}}" rel="stylesheet">
    <link href="{{asset('vendors/datatables.net-buttons-bs/css/buttons.bootstrap.min.css')}}" rel="stylesheet">
    <link href="{{asset('vendors/datatables.net-fixedheader-bs/css/fixedHeader.bootstrap.min.css')}}" rel="stylesheet">
    <link href="{{asset('vendors/datatables.net-responsive-bs/css/responsive.bootstrap.min.css')}}" rel="stylesheet">
    <link href="{{asset('vendors/datatables.net-scroller-bs/css/scroller.bootstrap.min.css')}}" rel="stylesheet">
    <link href="{{asset('vendors/msgbox/jquery.msgbox.css')}}" rel="stylesheet">
@endsection
@section('includesScripts')
    <script src="{{asset('vendors/pnotify/dist/pnotify.js')}}"></script>
    <script src="{{asset('vendors/pnotify/dist/pnotify.buttons.js')}}"></script>
    <script src="{{asset('vendors/pnotify/dist/pnotify.nonblock.js')}}"></script>
    <script src="{{asset('vendors/datatables.net/js/jquery.dataTables.min.js')}}"></script>
    <script src="{{asset('vendors/datatables.net-bs/js/dataTables.bootstrap.min.js')}}"></script>
    <script src="{{asset('vendors/datatables.net-buttons/js/dataTables.buttons.min.js')}}"></script>
    <script src="{{asset('vendors/datatables.net-buttons-bs/js/buttons.bootstrap.min.js')}}"></script>
    <script src="{{asset('vendors/datatables.net-buttons/js/buttons.flash.min.js')}}"></script>
    <script src="{{asset('vendors/datatables.net-buttons/js/buttons.html5.min.js')}}"></script>
    <script src="{{asset('vendors/datatables.net-buttons/js/buttons.print.min.js')}}"></script>
    <script src="{{asset('vendors/datatables.net-fixedheader/js/dataTables.fixedHeader.min.js')}}"></script>
    <script src="{{asset('vendors/datatables.net-keytable/js/dataTables.keyTable.min.js')}}"></script>
    <script src="{{asset('vendors/datatables.net-responsive/js/dataTables.responsive.min.js')}}"></script>
    <script src="{{asset('vendors/datatables.net-responsive-bs/js/responsive.bootstrap.js')}}"></script>
    <script src="{{asset('vendors/datatables.net-scroller/js/dataTables.scroller.min.js')}}"></script>
    <script src="{{asset('vendors/msgbox/jquery.msgbox.js')}}"></script>
    <script src="{{asset('build/js/datatables.js')}}"></script>
    <script src="{{asset('build/js/funtionsConfirm.js')}}"></script>
@endsection

resources/views/vacaciones/crear.blade.php
@extends('layouts.formModal')
@section('titulo','Vacaciones | Crear')
@section('nombrepagina','Nuevo registro')
@section('contenido')
{!! Form::open(['route' => 'registrar_vacaciones.store', 'method'=>'POST','id'=>'frm','name'=>'frm', 'class'=>'form-horizontal']) !!}
@include('vacaciones.forms.form_registro')
<div class="form-group" align='center'>
    {!!Form::submit('Crear',['class'=>'btn btn-sm btn-success','id'=>'btnuser'])!!}     
    <button type="button"  onclick="window.parent.location.href = '/vacaciones'" class="btn btn-sm btn-warning">Cancelar</button>
</div>
{!!Form::close()!!}

@stop

@section('includesCss')
    <link href="{{asset('vendors/iCheck/skins/flat/green.css')}}" rel="stylesheet">
@endsection
@section('includesScripts')
<script src="{{asset('vendors/moment/min/moment.min.js')}}"></script>
<script src="{{asset('vendors/bootstrap-daterangepicker/daterangepicker.js')}}"></script>
<script src="{{asset('vendors/bootstrap-datetimepicker/build/js/bootstrap-datetimepicker.min.js')}}"></script>
<script src="{{asset('vendors/validator/validator.js')}}"></script>

<script type="text/javascript">
	
	$(document).ready(function() {

	    $("#fecha_salida").change(function (event) {
	    	if($("#numero_dias").val() && event.target.value) {
		        $.get("/getfechaentrada/" + $("#numero_dias").val() + "/" + event.target.value, function (response, torres) {
		        	$("#fecha_entradaSpan").text(response);
		        	$("#fecha_entrada").val(response);		    
		        });
	    	}
	    
	    });
	    $("#numero_dias").change(function (event) {
	    	if($("#numero_dias").val() && event.target.value) {
		        $.get("/getfechaentrada/" + event.target.value + "/" + $("#fecha_salida").val(), function (response, torres) {
		        	$("#fecha_entradaSpan").text(response);
		        	$("#fecha_entrada").val(response);		    
		        });
	    	}
	    
	    });

	});
</script>
@endsection

resources/views/vacaciones/registrar.blade.php
@extends('layouts.app')
@section('titleForm','Registro de vacaciones por empleado')
@section('titleTab')
    <div class="title_right">
        <div class="col-md-5 col-sm-5 col-xs-12 form-group pull-right top_search">
            
        </div>
    </div>
@endsection
@section('content')
    <!-- page content -->
    <div class="center_col" role="main">
      <div class="">

        <div class="clearfix"></div>

        <div class="row">
          <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="x_panel">
              <div class="x_content">
                <div class="row">
                  <div class="col-sm-12">
                    <div class="card-box table-responsive">
                      <table id="datatable-keytable" class="table table-striped table-bordered">
                        <thead>
                          <tr>
                            <th>Numero de días</th>
                            <th>Fecha de salida</th>
                            <th>Fecha de entrada</th>
                            <th>Remuneración</th>
                            <th>Observaciones</th>
                            <th>Estado</th>
                            <th>Acción</th>
                          </tr>
                        </thead>

                        <tbody>
                            @foreach($empleados as $data)
                              <tr>  
                                <td>{{$data->numero_dias}}</td>
                                <td>{{$data->fecha_salida}}</td>
                                <td>{{$data->fecha_entrada}}</td>
                                @if($data->remuneracion === 1)
                                <td>No</td>
                                @else
                                <td>Si </td>
                                @endif
                                <td>{{$data->observaciones}}</td>
                                @if($data->estado === 1)
                                <td>Activo</td>
                                @else
                                <td>Ejecutada</td>
                                @endif

                                <td>
                                    {!!Html::decode(link_to_route('aplicar_altas_bajas.edit',
                                                            '<button class="btn-primary" title="Editar"><i class="fa fa-edit"></i></button>', [$data->id],
                                                                ['class'=>'iframe']))!!}
                                     
                                    <a onclick="changeEstado({{$data->id}}, 'estadoVacaciones/{{$data->id}}/', 'Perfil: {{$data->id}}');"><button class="btn-warning" title="Cambiar estado"><i class="fa fa-exchange"></i></button>
                                    </a>
                                    

                                   

                                </td>
                              </tr>
                            @endforeach
                              <div class="col-md-5 col-sm-5 col-xs-12 form-group pull-right top_search">
                                 <div class="input-group">
                                    <a class="form-control" placeholder="Search for...">Registrar Vacaciones</a>
                                    <span class="input-group-btn">                                        
                                        {!!Html::decode(
                                        link_to_route(
                                        'registrar_vacaciones.create',
                                        '<button class="btn btn-sm btn-warning"><i class="fa fa-plus-square"></i> <span style="color:#FFFFFF";>Agregar</span></button>',
                                        [$id],
                                        ['class'=>'iframe']
                                        ))!!}
                                    </span>
                                </div>
                              </div>
                        </tbody>
                      </table>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
@endsection
@section('includesCss')
    <link href="{{asset('vendors/pnotify/dist/pnotify.css')}}" rel="stylesheet">
    <link href="{{asset('vendors/pnotify/dist/pnotify.buttons.css')}}" rel="stylesheet">
    <link href="{{asset('vendors/pnotify/dist/pnotify.nonblock.css')}}" rel="stylesheet">
    <link href="{{asset('vendors/datatables.net-bs/css/dataTables.bootstrap.min.css')}}" rel="stylesheet">
    <link href="{{asset('vendors/datatables.net-buttons-bs/css/buttons.bootstrap.min.css')}}" rel="stylesheet">
    <link href="{{asset('vendors/datatables.net-fixedheader-bs/css/fixedHeader.bootstrap.min.css')}}" rel="stylesheet">
    <link href="{{asset('vendors/datatables.net-responsive-bs/css/responsive.bootstrap.min.css')}}" rel="stylesheet">
    <link href="{{asset('vendors/datatables.net-scroller-bs/css/scroller.bootstrap.min.css')}}" rel="stylesheet">
    <link href="{{asset('vendors/msgbox/jquery.msgbox.css')}}" rel="stylesheet">
    <link href="{{asset('vendors/color-box/colorbox.css')}}" rel="stylesheet">
@endsection
@section('includesScripts')
    <script src="{{asset('vendors/pnotify/dist/pnotify.js')}}"></script>
    <script src="{{asset('vendors/pnotify/dist/pnotify.buttons.js')}}"></script>
    <script src="{{asset('vendors/pnotify/dist/pnotify.nonblock.js')}}"></script>
    <script src="{{asset('vendors/datatables.net/js/jquery.dataTables.min.js')}}"></script>
    <script src="{{asset('vendors/datatables.net-bs/js/dataTables.bootstrap.min.js')}}"></script>
    <script src="{{asset('vendors/datatables.net-buttons/js/dataTables.buttons.min.js')}}"></script>
    <script src="{{asset('vendors/datatables.net-buttons-bs/js/buttons.bootstrap.min.js')}}"></script>
    <script src="{{asset('vendors/datatables.net-buttons/js/buttons.flash.min.js')}}"></script>
    <script src="{{asset('vendors/datatables.net-buttons/js/buttons.html5.min.js')}}"></script>
    <script src="{{asset('vendors/datatables.net-buttons/js/buttons.print.min.js')}}"></script>
    <script src="{{asset('vendors/datatables.net-fixedheader/js/dataTables.fixedHeader.min.js')}}"></script>
    <script src="{{asset('vendors/datatables.net-keytable/js/dataTables.keyTable.min.js')}}"></script>
    <script src="{{asset('vendors/datatables.net-responsive/js/dataTables.responsive.min.js')}}"></script>
    <script src="{{asset('vendors/datatables.net-responsive-bs/js/responsive.bootstrap.js')}}"></script>
    <script src="{{asset('vendors/datatables.net-scroller/js/dataTables.scroller.min.js')}}"></script>
    <script src="{{asset('vendors/msgbox/jquery.msgbox.js')}}"></script>
    <script src="{{asset('build/js/datatables.js')}}"></script>
    <script src="{{asset('build/js/funtionsConfirm.js')}}"></script>
    <script src="{{asset('vendors/color-box/jquery.colorbox.js')}}"></script>
    <script type="text/javascript">
        $(document).ready(function(){
            $(".iframe").colorbox({
                iframe: true,
                width: "70%",
                height: "70%"
            });
        });
    </script>
@endsection